{
 "title": "CannyLS",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "job", "query": "cannyls_device_status" },
   {
    "name": "instance",
    "query": "cannyls_device_status{ job=~\"$job\" }"
   },
   {
    "name": "device",
    "query": "cannyls_device_status { job=~\"$job\", instance=~\"$instance\" }"
   },
   {
    "name": "duration",
    "query": "5s,10s,15s,30s,1m,3m,5m,10m,15m,30m,1h"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Processes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(sum by (instance)(cannyls_device_status{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"}))"
    }
   ]
  },
  {
   "title": "Devices",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(cannyls_device_status{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"})"
    }
   ]
  },
  {
   "title": "Stopped Devices",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(cannyls_device_status{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"} == 0)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Lumps",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cannyls_storage_put_lumps_total{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"}) - sum(cannyls_storage_delete_lumps_total{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"})"
    }
   ]
  },
  {
   "title": "Device Queue Length (current)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cannyls_device_enqueued_commands_total{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"} - cannyls_device_dequeued_commands_total{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"})"
    }
   ]
  },
  {
   "title": "Device Queue Length (peak)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "short",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(cannyls_device_enqueued_commands_total{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"} - cannyls_device_dequeued_commands_total{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"})"
    }
   ]
  },
  {
   "title": "Storage Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cannyls_data_allocator_allocated_bytes_total{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"}) - sum(cannyls_data_allocator_released_bytes_total{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"})"
    }
   ]
  },
  {
   "title": "Storage Capacity",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cannyls_data_region_capacity_bytes{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"})"
    }
   ]
  },
  {
   "title": "Usage  Rate (device average)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(cannyls_data_allocator_allocated_bytes_total{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"}) - sum(cannyls_data_allocator_released_bytes_total{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"})) / sum(cannyls_data_region_capacity_bytes{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"})"
    }
   ]
  },
  {
   "title": "Usage Rate (max device)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "max((sum by(device)(cannyls_data_allocator_allocated_bytes_total{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"}) - sum by(device)(cannyls_data_allocator_released_bytes_total{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"})) / sum by(device)(cannyls_data_region_capacity_bytes{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"}))"
    }
   ]
  },
  {
   "title": "Journal Region Capacity",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cannyls_journal_queue_capacity_bytes{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"})"
    }
   ]
  },
  {
   "title": "Journal Region Usage Rate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(cannyls_journal_queue_consumed_bytes_total{job =~\"$job\", instance =~ \"$instance\", device =~ \"$device\"}) - sum(cannyls_journal_queue_released_bytes_total{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"})) / sum(cannyls_journal_queue_capacity_bytes{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"})"
    }
   ]
  },
  {
   "title": "PUT lumps (current)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(cannyls_storage_put_lumps_total{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"}[$duration]))"
    }
   ]
  },
  {
   "title": "PUT lumps (peak)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 9 },
   "format": "ops",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(rate(cannyls_storage_put_lumps_total{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"}[$duration]))"
    }
   ]
  },
  {
   "title": "DELETE lumps (current)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 9 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(cannyls_storage_delete_lumps_total{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"}[$duration]))"
    }
   ]
  },
  {
   "title": "DELETE lumps (peak)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 9 },
   "format": "ops",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(rate(cannyls_storage_delete_lumps_total{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"}[$duration]))"
    }
   ]
  },
  {
   "title": "GET lumps (peak)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 9 },
   "format": "ops",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(rate(cannyls_storage_get_lumps_total{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"}[$duration]))"
    }
   ]
  },
  {
   "title": "GET lumps (current)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 9 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(cannyls_storage_get_lumps_total{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"}[$duration]))"
    }
   ]
  },
  {
   "title": "Allocated Bytes (current)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 13 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(cannyls_data_allocator_allocated_bytes_total{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\", phase = \"running\"}[$duration]))"
    }
   ]
  },
  {
   "title": "Allocated Bytes (peak)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 13 },
   "format": "Bps",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(rate(cannyls_data_allocator_allocated_bytes_total{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\", phase = \"running\"}[$duration]))"
    }
   ]
  },
  {
   "title": "Released Bytes (current)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 13 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(cannyls_data_allocator_released_bytes_total{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"}[$duration]))"
    }
   ]
  },
  {
   "title": "Released Bytes (peak)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 13 },
   "format": "Bps",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(rate(cannyls_data_allocator_released_bytes_total{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"}[$duration]))"
    }
   ]
  },
  {
   "title": "Failed Operations",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 13 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(cannyls_device_failed_commands_total{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"}[$duration]))"
    }
   ]
  },
  {
   "title": "Allocator Fragmentations",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 13 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cannyls_data_allocator_inserted_free_portions_total{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"} - cannyls_data_allocator_removed_free_portions_total)"
    }
   ]
  },
  {
   "title": "Device",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Devices",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count by(instance)(cannyls_storage_header{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"})",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Stopped Devices",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "expr": "count by(instance,device)(cannyls_device_status{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"} == 0)"
      }
     ]
    },
    {
     "title": "Number of Requests",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by(command)(rate(cannyls_device_enqueued_commands_total{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"}[$duration]))",
       "legendFormat": "{{ command }}"
      }
     ]
    },
    {
     "title": "Number of Failed Operations",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by(instance, device)(rate(cannyls_device_failed_commands_total{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"}[$duration])) != 0",
       "legendFormat": "{{ device }}@{{ instance }}"
      }
     ]
    },
    {
     "title": "Queue Length (unit: instance)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(cannyls_device_enqueued_commands_total{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"} - cannyls_device_dequeued_commands_total{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"})",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Queue Length (unit: device)",
     "type": "heatmap",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 29 },
     "targets": [
      {
       "expr": "sum by (instance, device)(cannyls_device_enqueued_commands_total{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"} - cannyls_device_dequeued_commands_total{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"})"
      }
     ]
    },
    {
     "title": "Number of Background Task Executions",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cannyls_device_side_jobs_total{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"}[$duration]))",
       "legendFormat": "Total"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Lumps",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(cannyls_storage_put_lumps_total{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"}) - sum(cannyls_storage_delete_lumps_total{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"})",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Number of Lumps per Instance",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(instance)(cannyls_storage_put_lumps_total{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"}) - sum by(instance)(cannyls_storage_delete_lumps_total{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"})",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Journal Region",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Usage",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(cannyls_journal_queue_consumed_bytes_total{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"}) - sum(cannyls_journal_queue_released_bytes_total{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"})",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Usage Rate",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(sum(cannyls_journal_queue_consumed_bytes_total{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"}) - sum(cannyls_journal_queue_released_bytes_total{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"})) / sum(cannyls_journal_queue_capacity_bytes{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"})",
       "legendFormat": "Average"
      },
      {
       "expr": "max((sum by(device)(cannyls_journal_queue_consumed_bytes_total{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"}) - sum by(device)(cannyls_journal_queue_released_bytes_total{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"})) / sum by(device)(cannyls_journal_queue_capacity_bytes{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"}))",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Record Additions",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (type)(rate(cannyls_journal_queue_enqueued_records_total{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"}[$duration]))",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Record Removals",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (type)(rate(cannyls_journal_queue_dequeued_records_total{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"}[$duration]))",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Number of Records",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(type)(cannyls_journal_queue_enqueued_records_total{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"}) - sum by(type)(cannyls_journal_queue_dequeued_records_total{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"})",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Number of Enqueuing/Dequeuing of GC Records",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum (rate(cannyls_journal_region_gc_dequeued_records_total{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"}[$duration])) ",
       "legendFormat": "dequeue"
      },
      {
       "expr": "sum (rate(cannyls_journal_region_gc_enqueued_records_total{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"}[$duration])) ",
       "legendFormat": "enqueue"
      }
     ]
    }
   ]
  },
  {
   "title": "Data Region",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(cannyls_data_allocator_allocated_bytes_total{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"}) - sum(cannyls_data_allocator_released_bytes_total{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"})",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Usage Rate (unit: device)",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
     "targets": [
      {
       "expr": "(sum by (instance, device)(cannyls_data_allocator_allocated_bytes_total{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"}) - sum by (instance, device)(cannyls_data_allocator_released_bytes_total{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"})) / sum by (instance, device)(cannyls_data_region_capacity_bytes{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"})"
      }
     ]
    },
    {
     "title": "Usage per Instance",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum by(instance)(cannyls_data_allocator_allocated_bytes_total{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"}) - sum by(instance)(cannyls_data_allocator_released_bytes_total{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"})",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Usage (Top 10 Devices)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "topk(10, sum by(instance, device)(cannyls_data_allocator_allocated_bytes_total{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"}) - sum by(instance, device)(cannyls_data_allocator_released_bytes_total{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"}))",
       "legendFormat": "{{ device }}@{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Data Region Allocator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Allocate and Release Requests",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cannyls_data_allocator_allocated_portions_total{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"}[$duration]))",
       "legendFormat": "Allocate"
      },
      {
       "expr": "sum(rate(cannyls_data_allocator_released_portions_total{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"}[$duration]))",
       "legendFormat": "Release"
      }
     ]
    },
    {
     "title": "Allocated and Released Bytes",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cannyls_data_allocator_allocated_bytes_total{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\", phase = \"running\"}[$duration]))",
       "legendFormat": "Allocated"
      },
      {
       "expr": "sum(rate(cannyls_data_allocator_released_bytes_total{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\",}[$duration]))",
       "legendFormat": "Released"
      }
     ]
    },
    {
     "title": "Total Fragmentations",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(cannyls_data_allocator_inserted_free_portions_total{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"} - cannyls_data_allocator_removed_free_portions_total{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"})",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Fragmentations per Device",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
     "targets": [
      {
       "expr": "cannyls_data_allocator_inserted_free_portions_total{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"} - cannyls_data_allocator_removed_free_portions_total{job =~ \"$job\", instance =~ \"$instance\", device =~ \"$device\"}"
      }
     ]
    }
   ]
  }
 ]
}